"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def Even_Fibonacci_Sum(n: int = 1000) -> int:

    a: int = 1
    b: int = 2
    EFS: int = 0
    while n > b:
        if b % 2 == 0: EFS += b
        a, b = b, a + b
    return EFS

def Sum_Even_Fibonnaci(n: int = 1000) -> int:
  
    a: int = 1
    b: int = 2
    EFS = 0
    while n > b:
        EFS += b
        a, b = a + 2*b, 2*a + 3*b
    return EFS
    
print(Even_Fibonacci_Sum())
print(Sum_Even_Fibonnaci())